namespace LaoshiBot.Infrastructure.Constants
{
    public class AppConfigurationKeyNames
    {
        
        public const string LAOSHIBOT_SPEECH_SERVICES_ENDPOINT = "LAOSHIBOT_SPEECH_SERVICES_ENDPOINT";
        public const string LAOSHIBOT_SPEECH_SERVICES_KEY = "LAOSHIBOT_SPEECH_SERVICES_KEY";
        public const string LAOSHIBOT_SPEECH_SERVICES_REGION = "LAOSHIBOT_SPEECH_SERVICES_REGION";

        public const string LAOSHIBOT_TRANSLATOR_SERVICES_ENDPOINT = "LAOSHIBOT_TRANSLATOR_SERVICES_ENDPOINT";
        public const string LAOSHIBOT_TRANSLATOR_SERVICES_KEY = "LAOSHIBOT_TRANSLATOR_SERVICES_KEY";
        public const string LAOSHIBOT_TRANSLATOR_SERVICES_REGION = "LAOSHIBOT_TRANSLATOR_SERVICES_REGION";



        public const string LAOSHIBOT_OPENAI_ENDPOINT = "LAOSHIBOT_OPENAI_ENDPOINT";
        public const string LAOSHIBOT_OPENAI_KEY = "LAOSHIBOT_OPENAI_KEY";
        public const string LAOSHIBOT_OPENAI_REGION = "LAOSHIBOT_OPENAI_REGION";
        public const string LAOSHIBOT_OPENAI_DALLE_MODEL = "LAOSHIBOT_OPENAI_DALLE_MODEL";


        public const string LAOSHIBOT_STORAGE_CONNECTION_STRING = "LAOSHIBOT_STORAGE_CONNECTION_STRING";
    }
}
